package org.reldb.wrapd.sqldb;

import java.io.Serializable;

/**
 * The base class for all tuples. Derived classes are usually auto-generated by TupleTypeGenerator.
 */
public abstract class Tuple implements Serializable {

    private static final long serialVersionUID = 1L;
}
