version: '3.9'

services:
  postgres-db:
    image: postgres:14.2
    restart: always
    volumes:
      - db-data-wrapd_postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wrapd_testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  mysql-db:
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data-wrapd_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wrapd_testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    volumes:
      - mssqlvolume:/var/opt/mssql
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: pass@Word
    ports:
      - "1433:1433"

volumes:
  db-data-wrapd_postgresql:
    driver: local
  db-data-wrapd_mysql:
    driver: local
  mssqlvolume:
    driver: local
